---
- name: Install required packages
  package:
    name: [apt-transport-https, ca-certificates, curl, gnupg, lsb-release]
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
  when: ansible_os_family == 'Debian'

- name: Install Docker engine
  package:
    name: [docker-ce, docker-ce-cli, containerd.io]
    state: present

- name: Ensure docker service is enabled and started
  service:
    name: docker
    state: started
    enabled: true
